<h1>Slideshow</h1>
<div class="flexslider" id="slider_home">
					
	<ul class="slides">
		<li>
			<div class="itemin" style="background: url('https://cdn.shopify.com/s/files/1/0004/3686/3040/files/13_Knitwear_Hero_Desktop_1692x1060_e4ec6241-4da0-445c-8719-1a1ed32349ab_1600x.jpg') no-repeat;background-size: cover;background-position: center; height: 500px;">
			<div class="overlay"></div>
				<div class="inner_slider">
					<span>AW22</span>
					<h2>NEW ARRIVALS</h2>
					<div class="slider_more">
						<a class="button white" href="">Shop MENS</a>
						<a class="button white" href="">SHOP WOMENS</a>
					</div>
				</div>
			</div>
		</li>
		<li>
			<div class="itemin" style="background: url(https://cdn.shopify.com/s/files/1/0004/3686/3040/files/13_Knitwear_MensHero_Desktop_1692x1060_bbb113a0-20c8-4b5c-a7b3-77d7474e84d4_1600x.jpg) no-repeat;background-size: cover;background-position: center; height: 500px;">
			<div class="overlay"></div>
				<div class="inner_slider">
					<span>AW22</span>
					<h2>NEW ARRIVALS</h2>
					<div class="slider_more">
						<a class="button white" href="">Shop MENS</a>
						<a class="button white" href="">SHOP WOMENS</a>
					</div>
				</div>
			</div>
		</li>
	</ul>
  
</div>
<script type="text/javascript">
    require(['flexslider'],function(){
        jQuery(document).ready(function ($) {
            $('.flexslider').flexslider();
        });
    });
</script>