<div class="best_sellers">
	<div class="container">
		<h2>Best Sellers</h2>
		<div class="box_best_sellers">
			<div class="item_product">
				<div class="featured_img">
					<a class="af" href="#"><img src="<?php echo $block->getViewFileUrl('images/product/2.jpg');?>" /></a>
					<a class="ah" href="#"><img src="<?php echo $block->getViewFileUrl('images/product/1.jpg');?>" /></a>
				</div>
				<span class="product_title"><a href="#">Essential Rib Tank</a></span>
				<span class="product_title_category"><a href="#">Army</a></span>
				<span class="product_price">$39.95</span>
			</div>
			<div class="item_product">
				<div class="featured_img">
					<a class="af" href="#"><img src="<?php echo $block->getViewFileUrl('images/product/3.jpg');?>" /></a>
					<a class="ah" href="#"><img src="<?php echo $block->getViewFileUrl('images/product/4.jpg');?>" /></a>
				</div>
				<span class="product_title"><a href="#">Frankie Poplin Shirt</a></span>
				<span class="product_title_category"><a href="#">White</a></span>
				<span class="product_price">$79.95</span>
			</div>
			<div class="item_product">
				<div class="featured_img">
					<a class="af" href="#"><img src="<?php echo $block->getViewFileUrl('images/product/5.jpg');?>" /></a>
					<a class="ah" href="#"><img src="<?php echo $block->getViewFileUrl('images/product/6.jpg');?>" /></a>
				</div>
				<span class="product_title"><a href="#">Lebowski Cord Overshirt</a></span>
				<span class="product_title_category"><a href="#">Flint</a></span>
				<span class="product_price">$139.95</span>
			</div>
			<div class="item_product">
				<div class="featured_img">
					<a class="af" href="#"><img src="<?php echo $block->getViewFileUrl('images/product/7.jpg');?>" /></a>
					<a class="ah" href="#"><img src="<?php echo $block->getViewFileUrl('images/product/8.jpg');?>" /></a>
				</div>
				<span class="product_title"><a href="#">Jimmy BF Tee</a></span>
				<span class="product_title_category"><a href="#">Almond</a></span>
				<span class="product_price">$69.95</span>
			</div>
		</div>
		<div class="container_button">
			<a href="#" class="button black">View all products</a>
		</div>
	</div>
</div>