<div class="footer_section">
	<div class="container">
		<div class="three_columns footer">
			<div class="item_colums">
				<h3>Help</h3>
				<ul>
					<li><a href="#">Help Centre</a></li>
					<li><a href="#">Shipping</a></li>
					<li><a href="#">Returns</a></li>
				</ul>
			</div>
			<div class="item_colums">
				<h3>Discover</h3>
				<ul>
					<li><a href="#">Size Guide</a></li>
					<li><a href="#">Gift cards</a></li>
					<li><a href="#">Check Gift Card Balance</a></li>
				</ul>
			</div>
			<div class="item_colums">
				<h2>Spend & earn rewards</h2>
				<span>Join Academy Rewards to receive a $10 </br>Welcome reward and earn as you spend.</span>
				<div class="container_button noalign">
					<a class="button black" href="#">Join Now</a>
				</div>
			</div>
		</div>
		<div class="copyright">
			<span>© 2020 Academy Brand</span>
		</div>
	</div>
</div>