<div class="topbar">SPEND $99 AND GET FREE SHIPPING AUSTRALIA WIDE</div>
<div class="main_header">
	<div class="container">
		<div class="header">
			<div class="left_h">
				<ul>
					<li>
						<a href="#">Mens</a>
					</li>
					<li>
						<a href="#">Womens</a>
					</li>
					<li>
						<a href="#">Kids</a>
					</li>
					<li>
						<a href="#">Rewards</a>
					</li>
				</ul>
			</div>
			<div class="mid_h">
				<a href="#"><h1>academy</br><span>brand</span></h1></a>
			</div>
			<div class="right_h">
				<ul>
					<li>
						<a href="#">Search</a>
					</li>
					<li>
						<a href="#">Stores</a>
					</li>
					<li>
						<a href="#">Account</a>
					</li>
					<li>
						<a href="#">Cart</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>