<div class="four_columns">
	<div class="item_colums">
		<a href="#">
			<img src="<?php echo $block->getViewFileUrl('images/product/outwear.jpg');?>" />
		</a>
	</div>
	<div class="item_colums">
		<a href="#">
			<img src="<?php echo $block->getViewFileUrl('images/product/Sweats.jpg');?>" />
		</a>
	</div>
	<div class="item_colums">
		<a href="#">
			<img src="<?php echo $block->getViewFileUrl('images/product/layers.jpg');?>" />
		</a>
	</div>
	<div class="item_colums">
		<a href="#">
			<img src="<?php echo $block->getViewFileUrl('images/product/Knitwear.jpg');?>" />
		</a>
	</div>
</div>
<div class="container">
	<div class="three_columns featured_category">
		<div class="item_colums">
			<a href="#">
				<img src="<?php echo $block->getViewFileUrl('images/product/mens_category.jpg');?>" />
			</a>
			<div class="box_category">
				<a href="#">
					<h3>MENS</h3>
					<span class="button white" href="#">Shop now</span>
				</a>
			</div>
		</div>
		<div class="item_colums">
			<a href="#">
				<img src="<?php echo $block->getViewFileUrl('images/product/womens_category.jpg');?>" />
			</a>
			<div class="box_category">
				<a href="#">
					<h3>Womens</h3>
					<span class="button white" href="#">Shop now</span>
				</a>
			</div>
		</div>
		<div class="item_colums">
			<a href="#">
				<img src="<?php echo $block->getViewFileUrl('images/product/kids_category.jpg');?>" />
			</a>
			<div class="box_category">
				<a href="#">
					<h3>Kids</h3>
					<span class="button white" href="#">Shop now</span>
				</a>
			</div>
		</div>
	</div>
</div>