<div class="flexslider" id="slider_home">
	<div class="itemin" style="background: url('https://cdn.shopify.com/s/files/1/0004/3686/3040/files/13_Knitwear_Hero_Desktop_1692x1060_e4ec6241-4da0-445c-8719-1a1ed32349ab_1600x.jpg') no-repeat;background-size: cover;background-position: center; height: 520px;">
		<div class="inner_slider">
			<span>AW22</span>
			<h2>NEW ARRIVALS</h2>
			<div class="slider_more">
				<a class="button white" href="">Shop MENS</a>
				<a class="button white" href="">SHOP WOMENS</a>
			</div>
		</div>
	</div>
</div>