<div class="two_columns for_deal">
	<div class="item_colums">
		<h2>2 FOR DEALS</h2>
		<p>
		Get your wardrobe in order with our exclusive Academy '2 for' deals. They're here to stay so why not take advantage and double up on your essentials.
		<div class="container_button noalign">
			<a href="#" class="button black" >Shop Now</a>
		</div>
		</p>
	</div>
	<div class="item_colums" style="background: url('<?php echo $block->getViewFileUrl('images/10_Homepage_2-for-deals_LR_1000x.gif');?>') no-repeat;background-size: cover;background-position: center;">

	</div>
</div>